version: '3.9'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscaled
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # Replace with your Tailscale authentication key from https://login.tailscale.com/admin/settings/keys
      - TS_AUTHKEY=API_KEY_HERE
      # Optional: Uncomment and configure if you want to advertise routes or set up an exit node
      #- TS_EXTRA_ARGS=--advertise-exit-node
      #--advertise-routes=192.168.1.0/24 
    volumes:
      - tailscale-state:/var/lib/tailscale
    network_mode: host
    restart: unless-stopped

volumes:
  tailscale-state:
